version: '3.8'

services:
  finance-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./finance_tracker.db
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=true
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Uncomment for PostgreSQL database (production)
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: finance_tracker
  #     POSTGRES_USER: finance_user
  #     POSTGRES_PASSWORD: finance_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# volumes:
#   postgres_data:
